services:
  frontend-library:
    build: 
      context: front
      dockerfile: docker/development 
    ports:
      - 80:5173
    volumes:
      - ./front/app:/usr/src/app
    depends_on:
      - backend-library
    environment:
      - API_URL=http://backend-library:8000

  backend-library:
    build: 
      context: back/library
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./back/library/app:/app
    environment:
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_NAME=${MYSQL_DBNAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

    
